name: Ping Site

on:
  schedule:
    - cron: "0 0 */15 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Acessar login
        run: curl -A "Mozilla/5.0" https://tabelas.infinityfree.me/
